# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create!([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create!(name: 'Luke', movie: movies.first)

Bar.destroy_all

steves = Bar.create!({ name: "Steve's Tavern On The Avenue", location: "933 Central Ave, St. Petersburg, FL 33705", phone: "(727) 894-1004", hours: "1PM - 3AM", kind: "dive"})
steves.dive_ratings.create!({ cd_jukebox: true, sweet_caroline: true, pickeled: true, dollar_bills: true, writing_wall: true, mirror: true, pbr: true, domestic_sign: true, wash_hands: true, urinal_cake: true, smoking: true, dart_board: true })
masterys = Bar.create!({ name: "Mastery's Bar & Grill", location: "233 Central Ave, St. Petersburg, FL 33705", phone: "(727) 822-3070", hours: "9AM - 3AM", kind: "dive"})
masterys.dive_ratings.create!({ cd_jukebox: true, sweet_caroline: true, pickeled: true, dollar_bills: true, writing_wall: true, mirror: true, pbr: true, domestic_sign: true, wash_hands: true, urinal_cake: true, smoking: true, dart_board: true })
jwags = Bar.create!({ name: "JWags", location: "2312 4th St N, St. Petersburg, FL 33704", phone: "(727) 258-4881", hours: "12PM - 3AM", kind: "dive"})
jwags.dive_ratings.create!({ cd_jukebox: true, sweet_caroline: true, pickeled: true, dollar_bills: true, writing_wall: true, mirror: true, pbr: true, domestic_sign: true, wash_hands: true, urinal_cake: true, smoking: true, dart_board: true })
stinger = Bar.create!({ name: "The Stinger Bar", location: "2222 49th St S, St. Petersburg, FL 33711", phone: "(727) 327-9115", hours: "9AM - 3AM", kind: "dive"})
stinger.dive_ratings.create!({ cd_jukebox: true, sweet_caroline: true, pickeled: true, dollar_bills: true, writing_wall: true, mirror: true, pbr: true, domestic_sign: true, wash_hands: true, urinal_cake: true, smoking: true, dart_board: true })
boardwalk = Bar.create!({ name: "Boardwalk Tavern", location: "2600 54th Ave N, St. Petersburg, FL 33714", phone: "(727) 507-1200", hours: "10AM - 3AM", kind: "dive" })
boardwalk.dive_ratings.create!({ cd_jukebox: true, sweet_caroline: true, pickeled: true, dollar_bills: true, writing_wall: true, mirror: true, pbr: true, domestic_sign: true, wash_hands: true, urinal_cake: true, smoking: true, dart_board: true })
emerald = Bar.create!({ name: "Emerald Bar", location: "550 Central Avenue North, St. Petersburg, FL 33701", phone: "(727) 898-6054", hours: "12PM - 3AM", kind: "dive" })
emerald.dive_ratings.create!({ cd_jukebox: true, sweet_caroline: true, pickeled: true, dollar_bills: true, writing_wall: true, mirror: true, pbr: true, domestic_sign: true, wash_hands: true, urinal_cake: true, smoking: true, dart_board: true })
wilsons = Bar.create!({ name: "Wilson's Sports Lounge", location: "3030 4th St N, St. Petersburg, FL 33704", phone: "(727) 895-4219", hours: "10AM - 3AM", kind: "dive" })
wilsons.dive_ratings.create!({ cd_jukebox: true, sweet_caroline: true, pickeled: true, dollar_bills: true, writing_wall: true, mirror: true, pbr: true, domestic_sign: true, wash_hands: true, urinal_cake: true, smoking: true, dart_board: true })
fubar = Bar.create!({ name: "Fubar Downtown", location: "658 Central Ave, St. Petersburg, FL 33701", phone: "(727) 424-1809", hours: "12PM - 3AM", kind: "dive" })
fubar.dive_ratings.create!({ cd_jukebox: true, sweet_caroline: true, pickeled: true, dollar_bills: true, writing_wall: true, mirror: true, pbr: true, domestic_sign: true, wash_hands: true, urinal_cake: true, smoking: true, dart_board: true })
abbey = Bar.create!({ name: "Abbey Road", location: "974 58th St N, St. Petersburg, FL 33710", phone: "(727) 343-0304", hours: "12PM - 3AM", kind: "dive" })
abbey.dive_ratings.create!({ cd_jukebox: true, sweet_caroline: true, pickeled: true, dollar_bills: true, writing_wall: true, mirror: true, pbr: true, domestic_sign: true, wash_hands: true, urinal_cake: true, smoking: true, dart_board: true })
pelican = Bar.create!({ name: "Pelican Pub", location: "18 2nd St N, St. Petersburg, FL 33701", phone: "(727) 896-6329", hours: "1PM - 3AM", kind: "dive" })
pelican.dive_ratings.create!({ cd_jukebox: true, sweet_caroline: true, pickeled: true, dollar_bills: true, writing_wall: true, mirror: true, pbr: true, domestic_sign: true, wash_hands: true, urinal_cake: true, smoking: true, dart_board: true })
somethins = Bar.create!({ name: "Somethin' Different", location: "2420 Central Avenue North, St. Petersburg, FL 33712", phone: "(727) 322-0070", hours: "12PM - 3AM", kind: "dive" })
somethins.dive_ratings.create!({ cd_jukebox: true, sweet_caroline: true, pickeled: true, dollar_bills: true, writing_wall: true, mirror: true, pbr: true, domestic_sign: true, wash_hands: true, urinal_cake: true, smoking: true, dart_board: true })
flamingos = Bar.create!({ name: "Flamingos Sports Bar", location: "1230 9th St N, St. Petersburg, FL 33705", phone: "(727) 821-9397", hours: "12PM - 3AM", kind: "dive" })
flamingos.dive_ratings.create!({ cd_jukebox: true, sweet_caroline: true, pickeled: true, dollar_bills: true, writing_wall: true, mirror: true, pbr: true, domestic_sign: true, wash_hands: true, urinal_cake: true, smoking: true, dart_board: true })


cage = Bar.create!({ name: "Cage Brewing", location: "2001 1st Ave S, St. Petersburg, FL 33712", phone: "(727) 201-4278", hours: "1PM - 3AM", kind: "brewery" })
cage.brewery_ratings.create!({ ipa: true, apa: true, ale: true, hefe: true, porter: true, stout: true, pale: true, blonde: true, pilsner: true, growler: true, crowler: true, rail: true })
threedaughters = Bar.create!({ name: "3 Daughters", location: "222 22nd St S, St. Petersburg, FL 33712", phone: "(727) 495-6002", hours: "12PM - 3AM", kind: "brewery" })
threedaughters.brewery_ratings.create!({ ipa: true, apa: true, ale: true, hefe: true, porter: true, stout: true, pale: true, blonde: true, pilsner: true, growler: true, crowler: true, rail: true })
corner = Bar.create!({ name: "Right Around the Corner", location: "2244 Central Ave, St. Petersburg, FL 33712", phone: "(813) 360-0766", hours: "12PM - 3AM", kind: "brewery" })
corner.brewery_ratings.create!({ ipa: true, apa: true, ale: true, hefe: true, porter: true, stout: true, pale: true, blonde: true, pilsner: true, growler: true, crowler: true, rail: true })
pinallasale = Bar.create!({ name: "Pinellas Ale Works", location: "1962 1st Ave S, St. Petersburg, FL 33712", phone: "(727) 235-0970", hours: "10AM - 3AM", kind: "brewery" })
pinallasale.brewery_ratings.create!({ ipa: true, apa: true, ale: true, hefe: true, porter: true, stout: true, pale: true, blonde: true, pilsner: true, growler: true, crowler: true, rail: true })
flying = Bar.create!({ name: "Flying Boat Brewing Company", location: "1776 11th Ave N, St. Petersburg, FL 33713", phone: "(727) 800-2999", hours: "1PM - 3AM", kind: "brewery" })
flying.brewery_ratings.create!({ ipa: true, apa: true, ale: true, hefe: true, porter: true, stout: true, pale: true, blonde: true, pilsner: true, growler: true, crowler: true, rail: true })
greenbench = Bar.create!({ name: "Green Bench Brewing Company", location: "1133 Baum Ave N, St. Petersburg, FL 33705", phone: "(727) 800-9836", hours: "12PM - 3AM", kind: "brewery" })
greenbench.brewery_ratings.create!({ ipa: true, apa: true, ale: true, hefe: true, porter: true, stout: true, pale: true, blonde: true, pilsner: true, growler: true, crowler: true, rail: true })
avid = Bar.create!({ name: "Avid Brew Company", location: "1745 1st Ave S, St. Petersburg, FL 33712", phone: "(727) 388-6756", hours: "9AM - 3AM", kind: "brewery" })
avid.brewery_ratings.create!({ ipa: true, apa: true, ale: true, hefe: true, porter: true, stout: true, pale: true, blonde: true, pilsner: true, growler: true, crowler: true, rail: true })
stpetebrewing = Bar.create!({ name: "St. Pete Brewing Company", location: "544 1st Ave N, St. Petersburg, FL 33701", phone: "(727) 623-4837", hours: "9AM - 3AM", kind: "brewery" })
stpetebrewing.brewery_ratings.create!({ ipa: true, apa: true, ale: true, hefe: true, porter: true, stout: true, pale: true, blonde: true, pilsner: true, growler: true, crowler: true, rail: true })
cycle = Bar.create!({ name: "Cycle Brewing", location: "534 Central Ave, St. Petersburg, FL 33701", phone: "(727) 555-5555", hours: "10AM - 3AM", kind: "brewery" })
cycle.brewery_ratings.create!({ ipa: true, apa: true, ale: true, hefe: true, porter: true, stout: true, pale: true, blonde: true, pilsner: true, growler: true, crowler: true, rail: true })
overflow = Bar.create!({ name: "Overflow Brewing Company", location: "770 1st Ave N, St. Petersburg, FL 33701", phone: "(727) 914-0665", hours: "9AM - 3AM", kind: "brewery" })
overflow.brewery_ratings.create!({ ipa: true, apa: true, ale: true, hefe: true, porter: true, stout: true, pale: true, blonde: true, pilsner: true, growler: true, crowler: true, rail: true })
dissent = Bar.create!({ name: "Dissent Craft Brewing Company", location: "5518 Haines Rd N, St. Petersburg, FL 33714", phone: "(727) 342-0255", hours: "1PM - 3AM", kind: "brewery" })
dissent.brewery_ratings.create!({ ipa: true, apa: true, ale: true, hefe: true, porter: true, stout: true, pale: true, blonde: true, pilsner: true, growler: true, crowler: true, rail: true })
